### PR TITLE
Adding Traditional Chinese localization, JA Fastlane updates

### PR DESCRIPTION
**Pull request by imasaru**
rCN and rTW were provided by Android Studio. I tried to use zh-hant, but Android Studio didn't recognize it.

### CODE REVIEW

**Comment by imasaru** [comment]
@VitalikL Is this good?

**Comment by VitalikL** [comment]
@imasaru I suggest to keep Simplified under `values-zh` which will be also a fallback and add traditional under `values-zh-rTW`

Also for the Fastlane (play store) we must use below:

`zh-CN` for Simplified
`zh-TW` for Traditional

**Review by VitalikL — CHANGES_REQUESTED** [review]
See above

**Comment by imasaru** [comment]
@VitalikL gotcha.

**Comment by VitalikL** [comment]
@imasaru Can you also add `27` revision for new language. It was released today :)

**Pull request merged**
