### PR TITLE
Mini player

### PR DESCRIPTION
**Pull request by TinasheMzondiwa**
# What did you change:

Added Mini Player controls

# Screenshot/GIFs of this change

| Dark                        | Light                        |
| ----------------------------- | ---------------------------- |
| Dark  | Light

# Merge checklist

- [ ] Automated (unit/ui) tests
- [x] Manual tests

### CODE REVIEW

**Comment by VitalikL** [comment]
@TinasheMzondiwa The mini player seems to be working well. I assume right now it the sample audio correct?

Few things on the UI

1. The backward, play / pause icons. Are you using the icons that I provided in the clickup?
2. Please increase the bottom padding below the artist label. 
3. Add little bit more padding on the right, after the play button
4. Reduce spacing between backward and play / pause button slightly

**Comment by TinasheMzondiwa** [comment]
> @TinasheMzondiwa The mini player seems to be working well. I assume right now it the sample audio correct?
> 
> Few things on the UI
> 
> 1. The backward, play / pause icons. Are you using the icons that I provided in the clickup?
> 2. Please increase the bottom padding below the artist label.
> 3. Add little bit more padding on the right, after the play button
> 4. Reduce spacing between backward and play / pause button slightly

Yes sample audio for now.
Let me fix those UI issues

**Comment by VitalikL** [comment]
@TinasheMzondiwa Also the headphones icon looks much larger than other ones in the toolbar

**Review by VitalikL — CHANGES_REQUESTED** [review]
1. Change the font typeface from `bold` to `medium` (Lato-Medium) of the mini player title label.
2. The top & bottom paddings should be equal i.e the distance between top and the title of the track and the bottom and the artist of the track

**Review by VitalikL — APPROVED** [review]
🎵

**Pull request merged**
