### PR TITLE
Remove Quarterly color primary usages

### PR DESCRIPTION
**Pull request by TinasheMzondiwa**
# What did you change:

Removed quarterly `color_primary` usages in:

- [x] About
- [x] Settings
- [x] Read 
- [x] Bible

 
# Screenshot/GIFs of this change

| About                        | Settings                        |
| ----------------------------- | ---------------------------- |
| Light  | Dark

| Dark                        | Sepia                        |
| ----------------------------- | ---------------------------- |
| Light  | Dark

| Light                        | Dark                        |
| ----------------------------- | ---------------------------- |
| Light  | Dark

# Merge checklist

- [x] Automated (unit/ui) tests
- [x] Manual tests

### CODE REVIEW

**Review by VitalikL — CHANGES_REQUESTED** [review]
1. There is a major issue with the parallax cover. See attached video. Tested on Samsung Note9 (Android 8)

<details>
  <summary>Expand to see video</summary>

https://user-images.githubusercontent.com/4108258/130715740-c2247eb7-edd0-4be4-94e0-b41251ecebd2.mp4

</details>



2. There is a positioning issue with on the tablet. See screenshot below. (Tested on emulator, API 30)

<details>
  <summary>Expand to see screenshot</summary>

Screenshot_1629857677

</details>

3. In Dark / Sepia mode the toolbar remains white (Tested on emulator, API 30)

<details>
  <summary>Expand to see screenshot</summary>

Screenshot_1629857771


</details>

3. Bible version selection text is not visible in dark reader mode (Tested on emulator, API 30)

<details>
  <summary>Expand to see screenshot</summary>

Screenshot_1629857824


</details>

**Comment by TinasheMzondiwa** [comment]
@VitalikL All other issues fixed and I've reverted changes in the Read screen

**Comment by VitalikL** [comment]
@TinasheMzondiwa The parallax issue is fixed, however the navbar is colored with the featured color now.

In addition to that, Note9 has the issue that we should probably fix asap as well (it was also reported by some of the users). The bottom of the screen is slightly cut off:

Screenshot_20210826-094507_Sabbath School

**Comment by VitalikL** [comment]
@TinasheMzondiwa I see that you simply increase the bottom padding. Even though it fixes the particular issue on the Note9 - I want us to find the root cause of the issue and fix that.

**Pull request merged**
