### PR TITLE
Updates from develop

### PR DESCRIPTION
**Pull request by TinasheMzondiwa**

### CODE REVIEW

**Comment by VitalikL** [comment]
@TinasheMzondiwa Were you able to test the firebase with it too?

**Comment by TinasheMzondiwa** [comment]
> @TinasheMzondiwa Were you able to test the firebase with it too?

There's still one issue with the css style.
I'm investigating this more, should be related to firebase storage.
So please don't merge yet

**Comment by VitalikL** [comment]
The initial testing looks good to me. I will test on various devices for Firebase issue.

**Comment by VitalikL** [comment]
@TinasheMzondiwa Currently there is a bug on certain devices (Ex Samsung Galaxy S20, running Android 10). The back button from the `quarterly` screen results in flickering and immediate return to the same screen. i.e impossible to get to the list of quarterlies. DM me for the test credentials to test on real device

**Comment by TinasheMzondiwa** [comment]
> @TinasheMzondiwa Currently there is a bug on certain devices (Ex Samsung Galaxy S20, running Android 10). The back button from the `quarterly` screen results in flickering and immediate return to the same screen. i.e impossible to get to the list of quarterlies. DM me for the test credentials to test on real device

This is now fixed

**Pull request merged**
