### PR TITLE
Enable firebase database persistence

### PR DESCRIPTION
**Pull request by TinasheMzondiwa**

### CODE REVIEW

**Comment by VitalikL** [comment]
@TinasheMzondiwa Does it for sure makes both quarterly updates and offline mode work?

**Comment by TinasheMzondiwa** [comment]
I'll be closing this for now.
Looks like the latest quarterly disappeared after updating to this version.

Investigating more the issues with Firebase database

**Comment by VitalikL** [comment]
@TinasheMzondiwa Let's consider downgrading to the stable version

**Comment by VitalikL** [comment]
@TinasheMzondiwa I tested and it seems to be working

**Review by VitalikL — APPROVED** [review]
🔔

**Pull request merged**
