### PR TITLE
Updated Korean Localization for Android

### PR DESCRIPTION
**Pull request by iTwoman**
Hey @VitalikL , here's the Korean localization for Android, as requested. Feel free to let me know if you have any questions or concerns. Thanks!

### CODE REVIEW

**Comment by VitalikL** [comment]
Thank you so much @iTwoman ! Would love to have you in our slack group! If you are interested can you please email me - lim.vitaliy@gmail.com

**Comment by iTwoman** [comment]
Thank you for considering your invitation to me to your development team.

I feel great if i can join your mission, but what kind of contribution do I expect?

Thanks!

**Comment by VitalikL** [comment]
@iTwoman We welcome any help or contribution! Since you already familiar with Korean language perhaps you can help us with Korean Sabbath School content. 

Additionally we are currently planning new project, which of course, will be multi-lingual and we will need any help!

**Comment by iTwoman** [comment]
Thanks 
I hope i can help you in some ways.
I am excited to contribute if any.

What is your next feasible project?

**Pull request merged**
